name: Branch Workflow

on:
  push:
    branches-ignore:
      - 'release/*'
      - 'wip/**'
      - 'master'

jobs:
  main:
    name: Branch Workflow Job
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Checkout Co Partitioning App example
        uses: actions/checkout@v1

      - name: Gradle Unit Tests
        run: ./gradlew test
